version: '3.4'

services:
  api:
    container_name: api
    ports:
      - '5000:80'
    build:
      context: .
      dockerfile: API/Dockerfile
    depends_on:
      - 'mongo'
      - 'redis'
    networks:
      - 'hepsi-network'

  mongo:
    ports:
      - '27017:27017'
    container_name: mongo
    restart: always
    image: 'mongo:latest'
    networks:
      - 'hepsi-network'

  redis:
    ports:
      - '6379:6379'
    container_name: redis
    restart: always
    image: 'redis:latest'
    networks:
      - 'hepsi-network'

networks:
 hepsi-network:
    driver: bridge
